import { Injuries } from '@/store/slices/classesSlice.ts'

/** Maps the key of each injury type (e.g. `bicep-l`) to its full name string (e.g. `Left bicep`). */
export const injuryNameMap: Record<keyof Injuries, string> = {
    'abdomen': 'Abdomen',
    'ankle-l': 'Ankle (L)',
    'ankle-r': 'Ankle (R)',
    'back-upper': 'Upper Back',
    'back-lower': 'Lower Back',
    'bicep-l': 'Bicep (L)',
    'bicep-r': 'Bicep (R)',
    'calf-l': 'Calf (L)',
    'calf-r': 'Calf (R)',
    'chest-l': 'Chest (L)',
    'chest-r': 'Chest (R)',
    'ear-l': 'Ear (L)',
    'ear-r': 'Ear (R)',
    'elbow-l': 'Elbow (L)',
    'elbow-r': 'Elbow (R)',
    'foot-l': 'Foot (L)',
    'foot-r': 'Foot (R)',
    'forearm-l': 'Forearm (L)',
    'forearm-r': 'Forearm (R)',
    'groin': 'Groin',
    'hamstring-l': 'Hamstring (L)',
    'hamstring-r': 'Hamstring (R)',
    'hand-l': 'Hand (L)',
    'hand-r': 'Hand (R)',
    'head': 'Head',
    'hip-l': 'Hip (L)',
    'hip-r': 'Hip (R)',
    'jaw': 'Jaw',
    'knee-l': 'Knee (L)',
    'knee-r': 'Knee (R)',
    'neck': 'Neck',
    'quad-l': 'Quad (L)',
    'quad-r': 'Quad (R)',
    'ribs-l': 'Ribs (L)',
    'ribs-r': 'Ribs (R)',
    'shin-l': 'Shin (L)',
    'shin-r': 'Shin (R)',
    'shoulder-l': 'Shoulder (L)',
    'shoulder-r': 'Shoulder (R)',
    'wrist-l': 'Wrist (L)',
    'wrist-r': 'Wrist (R)',
}